### ISSUE TITLE
npm dependencies

### ISSUE THREAD

**Issue by jonkeller** [latentflip/dev-cert-authority#2]
Please modify readme npm command to:
`npm install -g dev-cert-authority mkdirp user-home` - install the module globally with npm, and a couple of dependencies

Without that, I was getting errors as shown below (this is on a Mac):

jon.keller@JonKMBP  ~/workspace  npm install -g dev-cert-authority
/usr/local/bin/dev-cert-authority -> /usr/local/lib/node_modules/dev-cert-authority/bin/dev-cert-authority
/usr/local/lib
└─┬ dev-cert-authority@1.1.0
  └── colors@1.1.2

 jon.keller@JonKMBP  ~/workspace  dev-cert-authority install
module.js:341
    throw err;
    ^

Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/dev-cert-authority/commands/install.js:1:78)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
 ✘ jon.keller@JonKMBP  ~/workspace  npm install -g mkdirp
/usr/local/bin/mkdirp -> /usr/local/lib/node_modules/mkdirp/bin/cmd.js
# 💚🔒 Dev Cert. Authority

/usr/local/lib
└─┬ mkdirp@0.5.1
  └── minimist@0.0.8

 jon.keller@JonKMBP  ~/workspace  dev-cert-authority install
module.js:341
    throw err;
    ^

Error: Cannot find module 'user-home'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/dev-cert-authority/paths.js:1:80)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
 ✘ jon.keller@JonKMBP  ~/workspace  npm install -g user-home
/usr/local/lib
└─┬ user-home@2.0.0
  └── os-homedir@1.0.1

 jon.keller@JonKMBP  ~/workspace  dev-cert-authority install
 ✅  Creating CA cert
Generating RSA private key, 2048 bit long modulus

**Comment by latentflip** [comment]
Wow, I'm an idiot and forgot to list dependencies, derp.

**Comment by latentflip** [comment]
@jonkeller thanks, added missing deps and published as 1.1.1

**Comment by jonkeller** [comment]
No problem - thank you for this tool. It really helped me out today.
